### ISSUE TITLE
[Fix] 최종QA

### ISSUE THREAD

**Issue by lydiacho** [sopt-makers/sopt-recruiting-frontend#280]
### 🦎 TODO
- [ ] makers - 이전기수활동여부 에서 해당사항 없음 제거 
- [ ] makers - 동아리를 알게 된 경로 제거 
- [ ] 인증번호 이메일 관련 안내문 내용 추가 
- [ ] 필수항목 점 위치 수정
