### ISSUE TITLE
[Fix] cursor: pointer 누락  

### ISSUE THREAD

**Issue by lydiacho** [sopt-makers/sopt-recruiting-frontend#83]
### 🦎 TODO
- [ ] `/` : 새지원서 작성하기 
- [ ] `/` : 비밀번호 재설정하기 
- [ ] `/apply` : 사진 input
- [ ] `/apply` : SelectBox, TextBox, CheckBox
- [ ] 에러페이지 : 이전 페이지로 가기, 문의하기 등

**Comment by eonseok-jeon** [comment]
앗 제 컴퓨터에선 Chrome이랑 Safari로 했을 때 둘 다 잘 되는데 혹시 지금도 안 될까요?

Textbox는 텍스트 입력하는 곳이라 pointer 보다 text cursor(현재 적용된 상태)가 더 좋을 거 같아요!
