### ISSUE TITLE
[Fix] input 값들 max length 테스트 해보기

### ISSUE THREAD

**Issue by eonseok-jeon** [sopt-makers/sopt-recruiting-frontend#98]
### 🦎 TODO
모든 input 값들 max length 들어왔을 때 처리되는지 테스트하기
<img width="770" alt="스크린샷 2024-07-03 오후 5 08 49" src="https://github.com/sopt-makers/sopt-recruiting-frontend/assets/121864459/42d6ed41-6408-45b8-bd23-e39cd28aa274">
![스크린샷 2024-07-23 오전 4 32 11](https://github.com/user-attachments/assets/1d624b10-96ed-4a32-809f-4cbe955ebf0d)

- [x] 파일 이름 테스트 완료
- [x] 지원자 이름 테스트 완료
- [x] 이메일 테스트 완료
